In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

In [2]:
df=pd.read_csv(r"C:\Users\saich\Downloads\Advertising.csv")
df.shape

(200, 5)

In [3]:
df.head()

Unnamed: 0     TV  Radio  Newspaper  Sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9

In [4]:
df.drop("Unnamed: 0",axis=1,inplace=True)

In [5]:
df.corr()

TV     Radio  Newspaper     Sales
TV         1.000000  0.054809   0.056648  0.782224
Radio      0.054809  1.000000   0.354104  0.576223
Newspaper  0.056648  0.354104   1.000000  0.228299
Sales      0.782224  0.576223   0.228299  1.000000

In [6]:
X=df[['TV', 'Radio', 'Newspaper']]
X.head()

TV  Radio  Newspaper
0  230.1   37.8       69.2
1   44.5   39.3       45.1
2   17.2   45.9       69.3
3  151.5   41.3       58.5
4  180.8   10.8       58.4

In [7]:
Y=df['Sales']
Y

0      22.1
1      10.4
2       9.3
3      18.5
4      12.9
       ... 
195     7.6
196     9.7
197    12.8
198    25.5
199    13.4
Name: Sales, Length: 200, dtype: float64

In [8]:
X.shape

(200, 3)

In [9]:
X=df[['TV','Radio','Newspaper']]
Y=df['Sales']
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2)

In [10]:
X_train.shape

(160, 3)

In [11]:
X_test.shape

(40, 3)

In [12]:
Y_train.shape

(160,)

In [13]:
Y_test.shape

(40,)

In [14]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(X_train,Y_train)

LinearRegression()

In [15]:
regressor.coef_

array([ 0.04611906,  0.18997883, -0.00113447])

In [16]:
regressor.intercept_

2.901696078545248

In [17]:
#y=(0.04627757*x1)+(0.19143052*x2)+(-0.00599346*x3)

In [18]:
regressor.predict(X_test)

array([12.6730545 , 17.1215491 , 16.07290382,  9.35176223, 20.94714272,
       15.64851797, 23.35314854,  7.02458888, 13.91898696, 12.19306132,
        7.10153287, 15.6692002 , 15.43906419,  6.56038502,  9.02542991,
       21.20952113,  9.9669402 , 13.78964107, 10.59282516, 20.07200117,
       11.88176159,  9.13564541,  9.78201076, 14.45733923,  4.45045277,
       15.35185753, 12.36899776, 17.40212085, 10.44727139, 19.23917224,
       17.85344889, 11.73519907, 12.41883377,  4.46823187, 20.54274034,
       15.04419501, 24.24040704, 14.80910826, 17.04621253, 23.5262733 ])

In [19]:
Y_pred_train=regressor.predict(X_train)

In [20]:
Y_pred_test=regressor.predict(X_test)

In [21]:
Y_pred_test

array([12.6730545 , 17.1215491 , 16.07290382,  9.35176223, 20.94714272,
       15.64851797, 23.35314854,  7.02458888, 13.91898696, 12.19306132,
        7.10153287, 15.6692002 , 15.43906419,  6.56038502,  9.02542991,
       21.20952113,  9.9669402 , 13.78964107, 10.59282516, 20.07200117,
       11.88176159,  9.13564541,  9.78201076, 14.45733923,  4.45045277,
       15.35185753, 12.36899776, 17.40212085, 10.44727139, 19.23917224,
       17.85344889, 11.73519907, 12.41883377,  4.46823187, 20.54274034,
       15.04419501, 24.24040704, 14.80910826, 17.04621253, 23.5262733 ])

In [22]:
Y_pred_train

array([13.92776591, 24.25317211,  8.45413809, 18.00959837, 15.13815238,
       20.03346484, 23.00264667, 12.95470997,  8.14788591, 19.33524928,
       19.78469459, 17.42498812, 10.10590532, 18.30128094, 18.21280667,
       13.22554012, 18.44604608, 12.50781163, 12.81187321, 16.44148409,
       13.67061656, 10.84592685,  9.70408332, 17.2538962 ,  8.8339752 ,
        9.50184047, 21.70262321, 13.59941225,  9.92204246,  9.15107654,
       14.81479603, 15.56063113,  6.47486139, 18.47444242, 10.5941972 ,
        3.55280483, 24.91460743, 10.02267561, 18.61922809, 16.61159622,
       22.0037742 , 18.01985933, 14.79259247, 12.00247397, 11.75818765,
       15.36007666,  7.88124228, 16.98824518, 15.63462668,  9.68813758,
        8.16781843, 16.46967582, 12.00912386,  7.6049182 , 22.36705718,
        6.81076847, 14.40506488,  7.63540266, 14.04860882,  7.84969323,
       17.35841201, 20.91533697, 11.48096795, 15.3937071 , 23.33945744,
       15.67989886,  5.28807222, 10.60846944, 14.2138591 , 12.82

In [23]:
Y_train

112    14.1
183    26.2
132     5.7
105    19.2
123    15.2
       ... 
167    12.2
199    13.4
189     6.7
72      8.8
187    17.3
Name: Sales, Length: 160, dtype: float64

In [24]:
X_train.head()

TV  Radio  Newspaper
112  175.7   15.4        2.4
183  287.6   43.0       71.8
132    8.4   27.2        2.1
105  137.9   46.4       59.0
123  123.1   34.6       12.4

In [1]:
y=(0.04611906*175.7)+(0.1899*15.4)+(-0.0011344*2.4)+2.954880862443101
y

13.979737144443101

In [2]:
y=(0.04611906*287.6)+(0.1899*43.0)+(-0.0011344*71.8)+2.954880862443101
y

24.302972598443105

In [27]:
# 15.59458137 value it predicted

In [28]:
# How are my predictions perfect to what level predictions also have some error know 

In [29]:
Y_test

96     11.7
27     15.9
178    11.8
51     10.7
137    20.8
87     16.0
101    23.8
10      8.6
100    11.7
177    11.7
107     8.7
25     12.0
156    15.3
117     9.4
66      9.5
69     22.3
18     11.3
174    11.5
12      9.2
176    20.2
75      8.7
125    10.6
138     9.6
120    15.5
76      6.9
146    13.2
1      10.4
74     17.0
130     1.6
92     19.4
70     18.3
88     12.9
179    12.6
91      7.3
39     21.5
26     15.0
98     25.4
110    13.4
64     18.0
36     25.4
Name: Sales, dtype: float64

In [30]:
Y_pred_test

array([12.6730545 , 17.1215491 , 16.07290382,  9.35176223, 20.94714272,
       15.64851797, 23.35314854,  7.02458888, 13.91898696, 12.19306132,
        7.10153287, 15.6692002 , 15.43906419,  6.56038502,  9.02542991,
       21.20952113,  9.9669402 , 13.78964107, 10.59282516, 20.07200117,
       11.88176159,  9.13564541,  9.78201076, 14.45733923,  4.45045277,
       15.35185753, 12.36899776, 17.40212085, 10.44727139, 19.23917224,
       17.85344889, 11.73519907, 12.41883377,  4.46823187, 20.54274034,
       15.04419501, 24.24040704, 14.80910826, 17.04621253, 23.5262733 ])

In [31]:
# Errors with General Example Adjusted R square lies between 0 and 1

In [32]:
#MAE
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [33]:
mse_train=mean_squared_error(Y_train,Y_pred_train)
mse_test=mean_squared_error(Y_test,Y_pred_test)
print(mse_train,"  ",mse_test)

2.299323976485044    4.740851927514633


In [34]:
mae_train=mean_absolute_error(Y_train,Y_pred_train)
mae_test=mean_absolute_error(Y_test,Y_pred_test)
print(mae_train,"  ",mae_test)

1.1742512582497704    1.52192419557398


In [35]:
rmse_train=np.sqrt(mean_squared_error(Y_train,Y_pred_train))
rmse_test=np.sqrt(mean_squared_error(Y_test,Y_pred_test))
print(rmse_train,"  ",rmse_test)

1.5163521940779603    2.1773497485508924


In [36]:
r2_score_train=r2_score(Y_train,Y_pred_train)
r2_score_test=r2_score(Y_test,Y_pred_test)
print(r2_score_train,"  ",r2_score_test)

0.9138354359398534    0.8345748945337653


In [37]:
n_train=X_train.shape[0]
n_train

160

In [38]:
n_test=X_test.shape[0]
n_test

40

In [39]:
p=len(X_train.columns)
p

3

In [40]:
adj_r2_score_train=1-(((1-r2_score_train)*(n_train-1))/(n_train-p-1))
adj_r2_score_test=1-(((1-r2_score_test)*(n_test-1))/(n_test-p-1))
print(adj_r2_score_train*100,"   ",adj_r2_score_test*100)

91.21784250925428     82.07894690782457


# Task exclude News paper Column and do the same and say whether They are useful or not

In [41]:
X=df[['TV', 'Radio']]
X.head()

TV  Radio
0  230.1   37.8
1   44.5   39.3
2   17.2   45.9
3  151.5   41.3
4  180.8   10.8

In [42]:
Y=df['Sales']
Y

0      22.1
1      10.4
2       9.3
3      18.5
4      12.9
       ... 
195     7.6
196     9.7
197    12.8
198    25.5
199    13.4
Name: Sales, Length: 200, dtype: float64

In [43]:
X.shape

(200, 2)

In [44]:
X=df[['TV','Radio']]
Y=df['Sales']
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2)

In [45]:
X_train.shape

(160, 2)

In [46]:
X_test.shape

(40, 2)

In [47]:
Y_train.shape

(160,)

In [48]:
Y_test.shape

(40,)

In [49]:
from sklearn.linear_model import LinearRegression
regressor1=LinearRegression()
regressor1.fit(X_train,Y_train)

LinearRegression()

In [50]:
regressor1.coef_

array([0.04492436, 0.19268285])

In [51]:
regressor1.intercept_

2.917588170849598

In [52]:
regressor1.predict(X_test)

array([18.06638321, 19.31647402,  7.00464885, 24.77933467,  7.57326016,
       11.85089851, 15.11460345, 15.79132892, 16.34251414, 16.65457153,
       21.09775415, 10.44002427, 14.14352874,  6.57424705,  6.52052178,
        9.89507559, 23.7508162 ,  5.34662524, 18.44424654, 14.56480123,
       22.25588423, 10.55320039, 13.23473226, 17.18723653, 11.96945275,
       13.12088711, 17.30480699, 20.88677997, 16.3030006 ,  8.7149684 ,
        8.92139697, 12.37949075,  9.10864994,  9.58657319, 12.53443003,
       21.22203397,  8.65992412, 16.28415199,  7.9072742 , 12.28389057])

In [53]:
Y_pred_train=regressor1.predict(X_train)

In [54]:
Y_pred_test=regressor1.predict(X_test)

In [55]:
Y_pred_test

array([18.06638321, 19.31647402,  7.00464885, 24.77933467,  7.57326016,
       11.85089851, 15.11460345, 15.79132892, 16.34251414, 16.65457153,
       21.09775415, 10.44002427, 14.14352874,  6.57424705,  6.52052178,
        9.89507559, 23.7508162 ,  5.34662524, 18.44424654, 14.56480123,
       22.25588423, 10.55320039, 13.23473226, 17.18723653, 11.96945275,
       13.12088711, 17.30480699, 20.88677997, 16.3030006 ,  8.7149684 ,
        8.92139697, 12.37949075,  9.10864994,  9.58657319, 12.53443003,
       21.22203397,  8.65992412, 16.28415199,  7.9072742 , 12.28389057])

In [56]:
Y_pred_train

array([23.22755575, 21.11596643, 21.52885768, 17.03263105,  8.99713887,
       17.68143036, 17.06052311,  7.943384  , 24.12319649, 10.96660941,
        8.14417968, 12.49079198, 20.81707841, 20.22759234, 13.83097404,
       12.48915822,  6.54062941, 14.33471686, 15.7136385 , 20.67409441,
       19.22048004, 20.0227239 , 11.92642375, 17.02623644, 12.38983273,
       16.43015957,  7.39892721, 21.37157608,  6.08913619,  9.17217355,
       11.49444135, 10.76336109, 17.45149042, 15.14233884, 15.79197066,
        6.87204636, 12.09408004,  9.83982147, 14.4804492 , 19.89582111,
       11.34222994, 18.42353527, 12.66115027, 17.35344983,  9.82909251,
       12.06664035, 14.98288665,  9.99846019,  7.80931947,  9.89692459,
       15.00160447,  8.76210286,  5.33689912, 13.73730192,  7.67103093,
       20.79430147, 14.67302031, 18.20614744, 18.50365105, 14.56531359,
        8.85486342, 17.14161044, 18.88140946, 11.7978218 , 21.69128028,
        5.70640709, 15.11051163, 12.73062153, 13.56388735, 16.31

In [57]:
Y_train

101    23.8
69     22.3
30     21.4
187    17.3
44      8.5
       ... 
27     15.9
139    20.7
191     9.9
75      8.7
151    11.6
Name: Sales, Length: 160, dtype: float64

In [58]:
Y_test

20     18.0
28     18.9
10      8.6
175    27.0
32      9.6
173    11.7
123    15.2
178    11.8
95     16.9
62     15.7
111    21.8
94     11.5
135    11.6
22      5.6
127     8.8
90     11.2
198    25.5
195     7.6
188    15.9
83     13.6
128    24.7
158     7.3
63     14.0
11     17.4
67     13.4
4      12.9
41     17.1
15     22.4
113    15.9
143    10.4
78      5.3
159    12.9
125    10.6
145    10.3
2       9.3
93     22.2
56      5.5
152    16.6
129     9.7
179    12.6
Name: Sales, dtype: float64

In [59]:
Y_pred_test

array([18.06638321, 19.31647402,  7.00464885, 24.77933467,  7.57326016,
       11.85089851, 15.11460345, 15.79132892, 16.34251414, 16.65457153,
       21.09775415, 10.44002427, 14.14352874,  6.57424705,  6.52052178,
        9.89507559, 23.7508162 ,  5.34662524, 18.44424654, 14.56480123,
       22.25588423, 10.55320039, 13.23473226, 17.18723653, 11.96945275,
       13.12088711, 17.30480699, 20.88677997, 16.3030006 ,  8.7149684 ,
        8.92139697, 12.37949075,  9.10864994,  9.58657319, 12.53443003,
       21.22203397,  8.65992412, 16.28415199,  7.9072742 , 12.28389057])

In [60]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [61]:
mse_train=mean_squared_error(Y_train,Y_pred_train)
mse_test=mean_squared_error(Y_test,Y_pred_test)
print(mse_train,"  ",mse_test)

2.705400585970681    3.1493071336506526


In [62]:
mae_train=mean_absolute_error(Y_train,Y_pred_train)
mae_test=mean_absolute_error(Y_test,Y_pred_test)
print(mae_train,"  ",mae_test)

1.2116970939078313    1.4179457174965058


In [63]:
rmse_train=np.sqrt(mean_squared_error(Y_train,Y_pred_train))
rmse_test=np.sqrt(mean_squared_error(Y_test,Y_pred_test))
print(rmse_train,"  ",rmse_test)

1.644810197551888    1.7746287312141242


In [64]:
r2_score_train=r2_score(Y_train,Y_pred_train)
r2_score_test=r2_score(Y_test,Y_pred_test)
print(r2_score_train,"  ",r2_score_test)

0.8974508050176198    0.8946398479920493


In [65]:
n_train=X_train.shape[0]
n_train

160

In [66]:
n_test=X_test.shape[0]
n_test

40

In [67]:
p=len(X_train.columns)
p

2

In [68]:
adj_r2_score_train=1-(((1-r2_score_train)*(n_train-1))/(n_train-p-1))
adj_r2_score_test=1-(((1-r2_score_test)*(n_test-1))/(n_test-p-1))
print(adj_r2_score_train*100,"   ",adj_r2_score_test*100)

89.61444458458698     88.89447046402682
